export class InvoiceProductModel{
  id:number;
  productId:number;
  name:string;
  productDescription:string;
  quantity:number;
  price:number;
  totalAmount:number;
  netAmount:number;
  discount:number;
  vat:number;
  tax:number;
  serialNo:number;
  expiredDate:Date;
  transId:number;
  unitQty:number;
  unitPrice:number;
  unitId:number;
}
