import { TransDetailsModel } from './../accounting/transaction/trans-details-model';
import { InvoiceProductModel } from './invoice.model';
export class SimpleInvoice {
   bankBranch:string;
   billerAddress:string;
   billerContactNo:string;
   billerName:string;
   billerCountry:string;
   billerEmail:string;
   branhcId:number;
   chequeDate:string;
   chequeNo:number;
   compId:number;
   totalDiscount:number;
   labourCost:number;
   netPayable:number;
   miscAdd:number;
   miscDeduct:number;
   paymentType:number;
   paidAmount:number;
   totalAmount:number;
   taxAmount:number;
   transId:number;
   partyId:number;
   voucherTypeId:number;
   moneyReceiptId:number;
   refNo:string;
   narration:string;
   refAccountId:number;
   transportCost:number;
   transType:string;
   userId:number;
   totalVat:number;
   invoiceDate:string;
   invoiceNo:number;
   invoiceType :string;
   salesBy:number;
   yearID:number;
   conRate:number;
   currencyRate:number;
   products:InvoiceProductModel[];
   transDetails:TransDetailsModel[];
}
