export class TransactionMasterAcc {
    id  : number;
	transId  : number;
	compId  : number;
	partyId : number;    
	voucherNo  : number;
	voucherDate   : string;
	voucherType   : string;
	refAccountId  : number;
    moneyReciptId:number;  
	transType  : number;    
	totalAmount  : number;    
	refNo  : string;    
	narration  : string;
    otherAddition:number;
    otherDeduction:number;
    transportCost:number;
    labourCost:number;
    paidAmount:number;
    payMode:number;
    billTo:number;
    billAddress:string;
    billContactNo:string;
	bankBranch  : string;
	chequeNo  : string;
	chequeDate  : string;
    empId:number;
    discountRate:number;
    discountAmount:number;
    vateRate:number;
	userId  : number;
	netPayable  : number;
	branchId  : number;
    currencyRate:number;
    salesPersonEmpCode:string;
	conRate  : number;    
	yearID : number;
    refBillId:number;
    formatVoucherNo:string;
    taxtAmount:number;
    taxtRate:number;
    billEmail:string;
    billCountry:string;
    approveStatus:number;
}
