export class AccountChartView {
    id    :number;
	lowerGroupId   :number;
	accountId   :number;
	proprietorName:number;
	accountName   :string ;
	aliasName  :string ;
	openningBalance  :number;
	currencyId  :number;
	currencyRate  :number;
	accType  :number;
	isBranch   :number;
	compId   :number;
	branchId  :number;
	isSubledger   :boolean;
	isBillbyBill   :boolean;
  isEmployee:boolean;
	isCostCenter   :boolean;
	headGroupID  :number ;
	balanceType  :number;
	isActive   :boolean;
	depriciationRate   :number;
	accountGroupId   :number;
	isSalesAccount  :boolean;
	creditLimit  :number;
	creditDays  :number;
	groupAccountID  :number;
	address : string;
	mobileNo : string;
	phoneNo : string;
	email : string;
	statusString :string;
	presentBalance:number;
	accountNo:string;
	country:string;
  tin:string;
  bin:string;
  criteriaID:number;
  parentID:number;
  detailsID:number;
  underCriteriaID:number;
  formateAccountName:string;
}
