import { HeadGroupName } from "../../head-group-name.model";
export class AccountChart1 {
	id    :number;
	lowerGroupId   :number;
	accountId   :number;
	proprietorName:number;
	accountName   :string ;
	aliasName  :string ;
	openningBalance  :number;
	currencyId  :number;
	currencyRate  :number;
	accType  :number;
	isBranch   :number;
	compId   :number;
	branchId  :number;
	isSubledger   :number;
	isBillbyBill   :number;
	isInventory   :number;
  isEmployee:number;
	isCostCenter   :number;
	headGroupID  :string ;
	headGroupName  :string ;
	balanceType  :number;
	isActive   :number;
	depriciationRate   :number;
	noteToHeadId  :number;
	accountGroupId   :number;
	isSalesAccount  :number;
	creditLimit  :number;
	creditDays  :number;
	entryTime   :Date;
	printPorder  :number;
	isBothBill  :number;
	commissionTypeID  :number;
	fcAcc  :number;
	createdBy  :string ;
	modifiedBy  :string ;
	modifiedDate  :string ;
	fcAmount  :number;
	groupAccountID  :number;
	address : string;
	isDefault :number;
	mobileNo : string;
	phoneNo : string;
	email : string;
	statusString :string;
	presentBalance:number;
	costCenter :string;
	subledger :string;
	inventory :string;
	billByBill :string;
	formateAccountName :string;
	lowerGroupName :string;
	groupName :string;
	accountNo:string;
	fromDate:string;
	toDate:string;
	country:string;
  tin:string;
  bin:string;
  criteriaID:number;
  parentID:number;
  detailsID:number;
  underCriteriaID:number;
  isIndependSubledger:number;
  subLeadeger:number;


}
// export class AccountChart {
//     id:number;
// 	  accountID:number;
// 	  lowerGroupID:number;
// 	  accountName:string;
//     aliasName:string;
//     accountNo:string;
// 	  openningBalance:number;
// 	  currencyID:number;
// 	  accType:number;
// 	  isSubledger:number;
// 	  isBillbyBill:number;
// 	  isCostCenter:number;
// 	  additionalGroupID:string;
// 	  additionalGroupName:string;
// 	  balanceType:number;
// 	  depriciationRate:number;
// 	  depriciationYear:number;
// 	  parentAccountID:number;
// 	  groupAccountID:number;
// 	  creditLimit:number;
// 	  creditDays:number;
// 	  currencyRate:number;
// 	  address:string;
// 	  mobileNo:string;
// 	  emailAddress:string;
// 	  commissionTypeID:number;
// 	  shortOrder:number;
// 	  isActive:number;
// 	  companyID:number;
// 	  createdDate :Date;
// 	  createdBy:string;
//     modifiedDate :Date;
// 	  modifiedBy:string;
//      headGroup:HeadGroupName[];
//      costCenter :string;
//      subledger :string;
//      inventory :string;
//      billByBill :string;
//      statusString :string;
//      presentBalance :number;
//        formateAccountName :string;
//       lowerGroupName :string;
//       groupName :string;
// }
